[package]
org = "kaneel"
name = "use_case"
version = "0.1.0"
distribution = "2201.3.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "persist"
version = "0.1.0"
repository = "local"